version: 2.1

jobs:
  build:
    working_directory: ~/calculator-test

    docker:
    - image: circleci/openjdk:8-jdk-browsers

  steps:

  - checkout

  - restore_cache:
      key: calculator-test-{{ checksum "pom.xml" }}

  - run: mvn dependency:go-offline

  - save_cache:
      paths:
      - ~/.m2
      key: calculator-test-{{ checksum "pom.xml" }}

  - run: mvn package

  - store_test_results:
      path: target/surefire-reports

  - store_artifacts:
      path: target/calculator-test-1.0-SNAPSHOT.jar